name: Coverage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    name: Continuous Integrations
    uses: ./.github/workflows/ci.yml
  coverage:
    name: Recalculate Coverage
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Update Coverage Report
        uses: ncruces/go-coverage-report@v0
        with:
          report: 'false'
          chart: 'false'
          amend: 'false'
        continue-on-error: true